function [coeffs, l] = fetch_mfcc(y,fs)
[coefficients,~,~,loc] = mfcc(y, fs, ...
                       'NumCoeffs',25, ...
                       'WindowLength',round(0.05*fs), ...
                       'OverlapLength',round(0.025*fs));
coeffs = coefficients;
l = loc;
end    