function [freqs, l] = fetch_pitch(y,fs)
windowLength = round(0.05*fs);
overlapLength = round(0.025*fs);
[f,loc] = pitch(y,fs, ...
    'WindowLength',windowLength, ...
    'OverlapLength',overlapLength, ...
    'Range',[50 150], ...
    'MedianFilterLength',3);
freqs = f;
l = loc;
end    