function [coeffs, l] = fetch_gfcc(y,fs)
[coefficients,~,~,loc] = gtcc(y,fs, ...
                       'NumCoeffs',25, ...
                       'FrequencyRange',[80,5000], ...
                       'WindowLength',round(0.05*fs), ...
                       'OverlapLength',round(0.025*fs));
coeffs = coefficients;
l = loc;
end    