function [speech_separation_net, mix_sequences_validation]  = ...
                                dnn_baseline(seqLen, mixture_sequences, ...
                                mixture_validation_sequences, ... 
                                mask_sequence_training, ...
                                mask_sequence_validation, ...
                                do_training,...
                                FFTLength)
    
    % 1. Reshape data which will be fed to the neural network based on
    % input
    mix_sequences_training  = reshape(mixture_sequences,    [1 1 (1 + FFTLength/2) * ...
                              seqLen size(mixture_sequences,4)]);
    mix_sequences_validation  = reshape(mixture_validation_sequences, [1 1 (1 + FFTLength/2) *... 
                                seqLen size(mixture_validation_sequences,4)]);
    mask_sequences_training = reshape(mask_sequence_training,   [1 1 (1 + FFTLength/2) * ...
                              seqLen size(mask_sequence_training,4)]);
    mask_sequence_validation = reshape(mask_sequence_validation,[1 1 (1 + FFTLength/2) * ...
                               seqLen size(mask_sequence_validation,4)]);
    
    % 2. Define a DNN with 5 layers. Input to the network being a matrix
    % of size 1x1x(1 + FFTLength/2)*seqLen (as only STFT features are used).
    % Each hidden layer having 2048 neurons and reLU activation and finally
    % an output fully connected layer with (1 + FFTLength/2)*seqLen neurons
    % as a regression layer.
    layers = [...
    imageInputLayer([1 1 (1 + FFTLength/2)*seqLen],"Normalization","None")

    fullyConnectedLayer((1 + FFTLength/2)*seqLen)
    batchNormalizationLayer
    reluLayer

    fullyConnectedLayer((1 + FFTLength/2)*seqLen)
    batchNormalizationLayer
    reluLayer

    fullyConnectedLayer((1 + FFTLength/2)*seqLen)
    batchNormalizationLayer
    reluLayer

    fullyConnectedLayer((1 + FFTLength/2)*seqLen)
    batchNormalizationLayer
    reluLayer

    fullyConnectedLayer((1 + FFTLength/2)*seqLen)
    regressionLayer
    ];

    maxEpochs     = 3; % Number of training epochs
    miniBatchSize = 16; % mini Batch size.

    options = trainingOptions("adam", ...
        "MaxEpochs",maxEpochs, ...
        "MiniBatchSize",miniBatchSize, ...
        "SequenceLength","longest", ...
        "Shuffle","every-epoch",...
        "Verbose",0, ...
        "Plots","training-progress",...
        "ValidationFrequency",floor(size(mix_sequences_training,4)/miniBatchSize),...
        "ValidationData",{mix_sequences_validation,mask_sequence_validation},...
        "LearnRateSchedule","piecewise",...
        "LearnRateDropFactor",0.9, ...
        "LearnRateDropPeriod",1, ...
        "ExecutionEnvironment", 'multi-gpu');
    
    if do_training
        speech_separation_net = trainNetwork(mix_sequences_training, ...
                                             mask_sequences_training,...
                                             layers,...
                                             options);
    else
        s = load("speech_separation_net.mat");
        speech_separation_net = s.speech_separation_net;
    end
end