numSamples=500;
num_Hidden_nodes=2000;
Number_of_features=4;
layers = [ sequenceInputLayer(Number_of_features);
    bilstmLayer(num_Hidden_nodes,"OutputMode","sequence");
    bilstmLayer(num_Hidden_nodes,"OutputMode","last");
    fullyConnectedLayer(numSamples)
    regressionLayer];

maxEpochs=5;
miniBatchSize=20; %To be decided keeping the sizes of features in mind to ensure minimum padding
options = trainingOptions('adam', ...
    'MaxEpochs',maxEpochs, ...
    'MiniBatchSize',miniBatchSize, ...
    'InitialLearnRate',0.01, ...
    'Shuffle','never', ...
    'Plots','training-progress',...
    'Verbose',0,...
    'ValidationData',{mix_sequences_validation,mask_sequence_validation}, ...
    'ValidationFrequency',floor(size(mix_sequences_training,4)/miniBatchSize), ...
    'LearnRateSchedule','piecewise', ...
    'LearnRateDropFactor',0.1, ...
    'LearnRateDropPeriod',20,...
    'SequenceLength','longest',...
    'ExecutionEnvironment','gpu');